---
title: "Covid Seasonality"
author: "Dan Warren & April Lamb"
date: "3/12/2021"
output: html_document
---

## Set working directory
```{r setup}
setwd('C:/Users/april/Desktop/Covid/from Dan')
```

## Packages
```{r load, include=FALSE}
library(ggeffects)
library(ggplot2)
library(mgcv)
library(raster)
library(DHARMa)
library(GGally)
library(dplyr)
library(lubridate)
library(vip)
library(ggpubr)
library(pdp)
```

## Data
```{r data}
covid.df <- read.csv("covidseasonality_long.csv", stringsAsFactors = TRUE)

covid.df$study <- as.factor(covid.df$study)

# Using lubridate to clean up dates for plotting
covid.df <- covid.df %>%
  mutate(date.my = as.Date(paste(covid.df$year, covid.df$month, 1, sep = "-")))

# Creating a column that scales each case observation by that study's max
# This is just for plotting, not for analysis
covid.df <- covid.df %>% group_by(study) %>%
  mutate(prop.study.max = cases/max(cases, na.rm = T))

# Split by virus type so these can be analyzed individually. We're only interested in the following four.
(covid.229E <- covid.df[covid.df$virus.type == "229E", ])
(covid.NL63 <- covid.df[covid.df$virus.type == "NL63", ])
(covid.OC43 <- covid.df[covid.df$virus.type == "OC43", ])
(covid.HKU1 <- covid.df[covid.df$virus.type == "HKU1", ])

```

## Mixed effects GAM by virus type 

```{r}
# 229E
analysis.df <- covid.229E[complete.cases(covid.229E),]
analysis.df <- droplevels(analysis.df)

mixedgam <- gamm(cases ~ 
                 s(month, bs = "cc", k = 12, by = virus.type) + 
                 s(latitude) + s(templow) + 
                 s(temphigh) + s(hum) + s(precip), 
                 random=list(study=~1),
               data = analysis.df, family = poisson)

plot(mixedgam$gam,pages=1)
summary(mixedgam$lme) # details of underlying lme fit
summary(mixedgam$gam) # gam style summary of fitted model
anova(mixedgam$gam) 
gam.check(mixedgam$gam) # simple checking plots
plot(ggpredict(mixedgam$gam)) # Plotting

# NL63
analysis.df <- covid.NL63[complete.cases(covid.NL63),]
analysis.df <- droplevels(analysis.df)

mixedgam <- gamm(cases ~ 
                 s(month, bs = "cc", k = 12, by = virus.type) + 
                 s(latitude) + s(templow) + 
                 s(temphigh) + s(hum) + s(precip), 
                 random=list(study=~1),
               data = analysis.df, family = poisson)

plot(mixedgam$gam,pages=1)
summary(mixedgam$lme) # details of underlying lme fit
summary(mixedgam$gam) # gam style summary of fitted model
anova(mixedgam$gam) 
gam.check(mixedgam$gam) # simple checking plots
plot(ggpredict(mixedgam$gam)) # Plotting

# OC43
analysis.df <- covid.OC43[complete.cases(covid.OC43),]
analysis.df <- droplevels(analysis.df)

mixedgam <- gamm(cases ~ 
                 s(month, bs = "cc", k = 12, by = virus.type) + 
                 s(latitude) + s(templow) + 
                 s(temphigh) + s(hum) + s(precip), 
                 random=list(study=~1),
               data = analysis.df, family = poisson)

plot(mixedgam$gam,pages=1)
summary(mixedgam$lme) # details of underlying lme fit
summary(mixedgam$gam) # gam style summary of fitted model
anova(mixedgam$gam) 
gam.check(mixedgam$gam) # simple checking plots
plot(ggpredict(mixedgam$gam)) # Plotting

# HKU1
analysis.df <- covid.HKU1[complete.cases(covid.HKU1),]
analysis.df <- droplevels(analysis.df)

mixedgam <- gamm(cases ~ 
                 s(month, bs = "cc", k = 12, by = virus.type) + 
                 s(latitude) + s(templow) + 
                 s(temphigh) + s(hum) + s(precip), 
                 random=list(study=~1),
               data = analysis.df, family = poisson)

plot(mixedgam$gam,pages=1)
summary(mixedgam$lme) # details of underlying lme fit
summary(mixedgam$gam) # gam style summary of fitted model
anova(mixedgam$gam) 
gam.check(mixedgam$gam) # simple checking plots
plot(ggpredict(mixedgam$gam)) # Plotting

```


