---
title: "Covid Seasonality"
author: "Dan Warren & April Lamb"
date: "3/12/2021"
output: html_document
---

### Set working directory
```{r setup, include=FALSE}
setwd('C:/Users/april/Desktop/Covid/from Dan')
```

### Packages
```{r load, include=FALSE}
pkgs <- c("ggeffects", "ggplot2", "mgcv", "raster", "DHARMa", "GGally", "dplyr", "lubridate", 
          "vip", "ggpubr", "pdp")

vapply(pkgs, library, logical(1), character.only = TRUE, logical.return = TRUE,
       quietly = TRUE)
```

### Data
```{r data}
covid.df <- read.csv("covidseasonality_long.csv", stringsAsFactors = TRUE)

covid.df$study <- as.factor(covid.df$study)

# Using lubridate to clean up dates for plotting
covid.df <- covid.df %>%
  mutate(date.my = as.Date(paste(covid.df$year, covid.df$month, 1, sep = "-")))

# Creating a column that scales each case observation by that study's max
# This is just for plotting, not for analysis
covid.df <- covid.df %>% group_by(study) %>%
  mutate(prop.study.max = cases/max(cases, na.rm = T))

# Split by virus type so these can be analyzed individually. We're only interested in the following four.
(covid.229E <- covid.df[covid.df$virus.type == "229E", ])
(covid.NL63 <- covid.df[covid.df$virus.type == "NL63", ])
(covid.OC43 <- covid.df[covid.df$virus.type == "OC43", ])
(covid.HKU1 <- covid.df[covid.df$virus.type == "HKU1", ])

covid.df <- rbind(covid.229E, covid.HKU1, covid.NL63, covid.OC43)

```

### Models

First lets look at all viruses. We'll run the GAM under a negative binomal distribution which has previously shown to best fit the data
```{r all}
# Drop missing data
analysis.df <- covid.df[complete.cases(covid.df),]
analysis.df <- droplevels(analysis.df)
length(unique(analysis.df$study)) # We have 22 unique studies

# Negative binomial
testgam <- gam(cases ~ virus.type + 
                 s(study, bs = "re") +
                 s(month, bs = "cc", k = 12, by = virus.type) + 
                 s(latitude) + s(templow) + 
                 s(temphigh) + s(hum) + s(precip), 
               data = analysis.df, family = nb(link=log), method="REML")

gam.check(testgam)
plot(ggpredict(testgam)) # plotting

### DHARMa simulations are not compatible with extended families, such as negative binomial ###
```
 
229E
```{r 229E}
analysis.df <- covid.229E[complete.cases(covid.229E),]
analysis.df <- droplevels(analysis.df) 
length(unique(analysis.df$study)) # 15 unique studies

# Negative binomial
testgam <- gam(cases ~ 
                 s(study, bs = "re") +
                 s(month, bs = "cc", k = 12) + 
                 s(latitude) + s(templow) + 
                 s(temphigh) + s(hum) + s(precip), 
               data = analysis.df, family = nb(link=log), method="REML")

gam.check(testgam)
plot(ggpredict(testgam)) # plotting

### DHARMa simulations are not compatible with extended families, such as negative binomial ###
```

NL63
```{r NL63}
analysis.df <- covid.NL63[complete.cases(covid.NL63),]
analysis.df <- droplevels(analysis.df)
length(unique(analysis.df$study)) # 18 unique studies

# Negative binomial
testgam <- gam(cases ~ 
                 s(study, bs = "re") +
                 s(month, bs = "cc", k = 12) + 
                 s(latitude) + s(templow) + 
                 s(temphigh) + s(hum) + s(precip), 
               data = analysis.df, family = nb(link=log), method="REML")

gam.check(testgam)
plot(ggpredict(testgam)) # plotting

### DHARMa simulations are not compatible with extended families, such as negative binomial ###
```

OC43
```{r OC43}
analysis.df <- covid.OC43[complete.cases(covid.OC43),]
analysis.df <- droplevels(analysis.df)
length(unique(analysis.df$study)) # 13 unique studies

# Negative binomial
testgam <- gam(cases ~ 
                 s(study, bs = "re") +
                 s(month, bs = "cc", k = 12) + 
                 s(latitude) + s(templow) + 
                 s(temphigh) + s(hum) + s(precip), 
               data = analysis.df, family = nb(link=log), method="REML")

gam.check(testgam)
plot(ggpredict(testgam)) # plotting

### DHARMa simulations are not compatible with extended families, such as negative binomial ###
```

HKU1
```{r HKU1}
analysis.df <- covid.HKU1[complete.cases(covid.HKU1),]
analysis.df <- droplevels(analysis.df)
length(unique(analysis.df$study)) # 13 unique studies

# Negative binomial
testgam <- gam(cases ~ 
                 s(study, bs = "re") +
                 s(month, bs = "cc", k = 12) + 
                 s(latitude) + s(templow) + 
                 s(temphigh) + s(hum) + s(precip), 
               data = analysis.df, family = nb(link=log), method="REML")

gam.check(testgam)
plot(ggpredict(testgam)) # plotting

### DHARMa simulations are not compatible with extended families, such as negative binomial ###
```
